"""
EW sourcing-bot — Option 2: Haiku extracts, Python composes.

All bot replies are generated by Python templates picked by a state
machine over (status, intent, spec_completeness, has_results, time_of_day).
Haiku's only job is to parse the user's SMS into structured JSON.

The webhook bid-intake yield logic is unchanged: any inbound with a VIN
or photo, or from any non-gated phone, falls straight through to the
existing Phase 1 / Phase 2 bid flow with zero interception.
"""
import os
import json
import threading
from datetime import datetime, timezone
try:
    from zoneinfo import ZoneInfo
    _ET = ZoneInfo('America/New_York')
except ImportError:
    import pytz
    _ET = pytz.timezone('America/New_York')


# ── Config ────────────────────────────────────────────────────────────────
_GATE = os.getenv('SOURCING_PHONE_GATE', '+14074309675')
_GATED_PHONES = {p.strip() for p in _GATE.split(',') if p.strip()}
_GATE_OPEN = '*' in _GATED_PHONES
_ACTIVE_DAYS = 7


# ── Bid-intake yield (unchanged from prior versions) ──────────────────────
def _looks_like_bid_intake(body, num_media=0):
    if num_media:
        return True
    if not body:
        return False
    import re
    if re.search(r'\b[A-HJ-NPR-Z0-9]{17}\b', body, re.IGNORECASE):
        return True
    return False


def _phone_allowed(phone):
    if _GATE_OPEN:
        return True
    return phone in _GATED_PHONES


# ── Async Twilio send ────────────────────────────────────────────────────
def _send_sms_async(send_sms, phone, text):
    if not send_sms or not phone or not text:
        return
    threading.Thread(target=send_sms, args=(phone, text), daemon=True).start()


# ── Conversation helpers ─────────────────────────────────────────────────
def _append_msg(conversation, role, text, raw=None):
    entry = {
        'role': role,
        'ts': datetime.now(timezone.utc).isoformat(),
        'text': text,
    }
    if raw is not None:
        entry['raw'] = raw
    return (conversation or []) + [entry]


def _find_active(cur, phone):
    cur.execute("""
        SELECT * FROM sourcing_requests
        WHERE phone = %s
          AND status <> 'archived'
          AND last_msg_at > NOW() - INTERVAL '%s days'
        ORDER BY last_msg_at DESC
        LIMIT 1
    """, (phone, _ACTIVE_DAYS))
    return cur.fetchone()


_STOP_KEYWORDS = ('stop', 'unsubscribe', 'quit', 'cancel')
_DROP_KEYWORDS = ('drop it', 'dropit', 'drop that', 'nevermind', 'never mind')


def _handle_stop_or_drop(cur, phone, body_lc, active):
    if active and any(k == body_lc or body_lc.startswith(k + ' ') for k in _DROP_KEYWORDS):
        new_conv = _append_msg(active.get('conversation'), 'user', body_lc)
        cur.execute("""UPDATE sourcing_requests
                          SET status='archived', archived_at=NOW(),
                              archive_reason='dropped',
                              conversation=%s::jsonb,
                              last_msg_at=NOW(), last_inbound_at=NOW()
                        WHERE id=%s""",
                    (json.dumps(new_conv), active['id']))
        return True
    if active and body_lc in _STOP_KEYWORDS:
        cur.execute("""UPDATE sourcing_requests
                          SET status='archived', archived_at=NOW(),
                              archive_reason='stopped'
                        WHERE id=%s""", (active['id'],))
        return True
    return False


# ── Reply templates (Python composes everything user sees) ───────────────
def _format_match(m):
    from sourcing_gemini import _fmt_miles
    ec = m.get('ext_color')
    ic = m.get('int_color')
    if ec and ic: color = f"{ec} / {ic}"
    elif ec: color = ec
    elif ic: color = f"{ic} interior"
    else: color = ''
    head = ' '.join(p for p in [str(m.get('year') or ''), str(m.get('model') or ''), str(m.get('trim') or '')] if p).strip()
    pieces = [head]
    if color: pieces.append(color)
    pieces.append(_fmt_miles(m.get('mileage')))
    return ', '.join(pieces)


def _short_desc(row):
    parts = []
    if row.get('year_min') or row.get('year_max'):
        if row.get('year_min') == row.get('year_max'):
            parts.append(str(row.get('year_min')))
        else:
            parts.append(f"{row.get('year_min','?')}-{row.get('year_max','?')}")
    for k in ('make', 'model', 'trim'):
        if row.get(k):
            parts.append(row[k])
    s = ' '.join(parts) or 'your search'
    if row.get('ext_color'):
        s += f" in {row['ext_color'][0]}"
    return s


def _present_results(matches):
    body = '\n'.join(_format_match(m) for m in matches[:3])
    n = len(matches)
    if n > 3:
        return f"{body}\ngot {n} total — want to see the rest?"
    if n > 1:
        return f"{body}\nany of these work?"
    return f"{body}\ninterested?"


def _no_match_offer(row, available_models):
    """Build relaxation menu or model-suggestion based on what's set."""
    if available_models and row.get('make'):
        top = available_models[0].get('model', '')
        hint = (row.get('model') or '').lower()
        if hint and (hint in top.lower() or top.lower().startswith(hint)):
            return f"got it. did you mean a {top}?"
        names = [m.get('model', '') for m in available_models[:4] if m.get('model')]
        if names:
            return f"got it. we've got {', '.join(names)}. any of those?"
        return "got it. any specific model in mind?"

    opts = []
    if row.get('ext_color'): opts.append("other colors")
    if row.get('trim'):      opts.append("other trims")
    if row.get('year_min') or row.get('year_max'): opts.append("other years")
    if row.get('miles_max'): opts.append("a higher mileage cap")
    if opts:
        return f"nothing matching that right now. want me to look at {', '.join(opts)}, or flag it for when one shows up?"
    return "nothing matching right now. want me to flag it for when one shows up?"


# ── Trim-only ambiguity probe ────────────────────────────────────────────
# These trim names span multiple makes — when the user mentions only a trim
# (no fresh make this turn) we ask "still {make}, or open to other makes?"
_AMBIGUOUS_TRIMS = {
    'gts', 'turbo', 'turbo s', 's', 'gt', 'gt s', 'touring',
    'sport', 'sport+', 'amg gt', 'gt2', 'gt4',
}
_MAKE_SPECIFIC_TRIMS = {
    # Trims that imply a make — no probe needed
    'carrera', 'gt3', 'targa', 'panamera', 'macan', 'cayenne', '911', '718',  # porsche
    'amg', 'g63', 'g550', 'g-class', 'g class',  # mercedes
    'm3', 'm4', 'm5', 'm8', 'x6m',  # bmw
    'rs', 'r8',  # audi
}


def _is_ambiguous_trim_pivot(row, parsed, user_text):
    """True if user's message looks like a bare trim name without a fresh make,
    AND the trim is cross-make. We probe before searching."""
    su = parsed.get('spec_update') or {}
    new_make = (su.get('make') or '').strip().lower()
    if new_make:
        return False  # user named the make this turn — no ambiguity
    new_trim = (su.get('trim') or '').strip().lower()
    body_lc = (user_text or '').strip().lower()
    if not row.get('make'):
        return False  # no current make — fall through to standard "what make?" ask

    candidate = new_trim or body_lc
    candidate = candidate.strip()
    if not candidate:
        return False
    if candidate in _MAKE_SPECIFIC_TRIMS:
        return False
    if candidate in _AMBIGUOUS_TRIMS:
        return True
    # Heuristic: short single-word query that matches a known ambiguous trim substring
    for trim in _AMBIGUOUS_TRIMS:
        if trim in candidate.split():
            return True
    return False


# ── State machine: pick the next reply + state ───────────────────────────
def _decide(row, parsed, search_results, available_models, user_text):
    """Returns (reply_text, next_state, did_search). Pure function — no I/O."""
    from sourcing_gemini import handoff_line

    intent = parsed.get('intent') or 'unclear'
    su = parsed.get('spec_update') or {}
    has_make  = bool(row.get('make'))
    has_model = bool(row.get('model'))
    has_year  = bool(row.get('year_min') or row.get('year_max'))
    has_name  = bool(row.get('customer_name'))
    status    = row.get('status', 'gathering')

    # ── Stop / drop intents
    if intent == 'stop':
        return ("ok, stopped. text us anytime.", 'archived', False)
    if intent == 'drop_it':
        return ("ok, dropped. text us anytime.", 'archived', False)

    # ── Name capture
    if intent == 'name_provided' and has_name:
        return (handoff_line(row['customer_name']), 'matched', False)

    # ── Wishlist save
    if intent == 'extend_wishlist':
        desc = _short_desc(row)
        if has_name:
            return (f"done, {row['customer_name'].split()[0]}. saved: {desc}. text 'drop it' anytime.", 'wishlist', False)
        return (f"done. saved: {desc}. text 'drop it' anytime. and what's your name so we know who to text?", 'wishlist', False)

    # ── More-details / MSRP / options request
    if intent == 'more_details' or 'msrp' in (user_text or '').lower() or 'options' in (user_text or '').lower() or 'where is' in (user_text or '').lower() or 'where are' in (user_text or '').lower() or 'location' in (user_text or '').lower():
        if has_name:
            return (f"don't have that info on hand — but if you're interested we can find out and come back to you, {row['customer_name'].split()[0]}.", 'presented', False)
        return ("don't have that info on hand — but if you're interested we can find out and come back to you. what's your name so we know who to text?", 'presented', False)

    # ── Interested
    if intent == 'interested':
        if has_name:
            return (handoff_line(row['customer_name']), 'matched', False)
        return ("if you want it we'll get back to you with all the details. what's your name so we know who to text?", 'presented', False)

    # ── More results pagination
    if intent == 'more_results' and search_results and len(search_results) > 3:
        # NOTE: pagination not yet wired (we always show top 3). For now treat as "any of those?"
        return (_present_results(search_results), 'presented', False)

    # ── Ambiguous-trim probe (before search)
    if _is_ambiguous_trim_pivot(row, parsed, user_text):
        return (f"still {row['make']}, or open to other makes?", status, False)

    # ── Spec gathering — ask for missing hard fields
    if not has_make:
        return ("got it. what make and model are you looking at?", 'gathering', False)
    if not has_model:
        return (f"got it. what {row['make']} model?", 'gathering', False)
    if not has_year:
        return (f"got it. what year range?", 'gathering', False)

    # ── Hard minimums met → search
    if search_results is not None:
        if search_results:
            return (_present_results(search_results), 'presented', True)
        return (_no_match_offer(row, available_models), 'presented', True)

    # Should not happen — caller always runs search when hard mins met.
    return ("got it.", status, False)


# ── Main turn handler ────────────────────────────────────────────────────
def _run_turn(db, cur, request_id, row, user_text, num_media=0,
              send_sms=None, phone=None, fresh_row=False):
    """Single turn: append user msg, Haiku-extract, Python-decide, persist, send."""
    from sourcing_gemini import extract as haiku_extract, merge_spec

    # 1. Append user msg to row's working conversation
    row['conversation'] = _append_msg(row.get('conversation') or [], 'user', user_text)

    # 2. Haiku extracts {intent, spec_update, spec_clear}
    parsed = haiku_extract(row, user_text)
    if parsed is None:
        # Haiku failed — fallback ack so user isn't stranded
        fallback = "got it — one sec."
        row['conversation'] = _append_msg(row['conversation'], 'bot', fallback)
        cur.execute("UPDATE sourcing_requests SET conversation=%s::jsonb, last_msg_at=NOW(), last_inbound_at=NOW() WHERE id=%s",
                    (json.dumps(row['conversation']), request_id))
        db.commit()
        if send_sms and phone:
            _send_sms_async(send_sms, phone, fallback)
        print(f'[sourcing] haiku-fallback id={request_id}', flush=True)
        return

    # 3. Apply spec changes BEFORE state-machine decision so it sees current spec
    spec_update = parsed.get('spec_update') or {}
    spec_clear = parsed.get('spec_clear') or []
    changes = merge_spec(row, spec_update, spec_clear=spec_clear)

    # 4. Decide whether we need to search
    has_make  = bool(row.get('make'))
    has_model = bool(row.get('model'))
    has_year  = bool(row.get('year_min') or row.get('year_max'))
    intent = parsed.get('intent') or 'unclear'

    needs_search = False
    if intent == 'sourcing' and has_make and has_model and has_year:
        needs_search = True
    elif intent == 'more_results' and has_make and has_model and has_year:
        # Re-run the search to surface the next batch. Pagination via
        # shown_inventory_ids is a TODO; for now we re-present, which at
        # least confirms count and gives the user something instead of
        # a dead-end "got it."
        needs_search = True
    elif intent in ('interested', 'extend_wishlist', 'drop_it', 'stop',
                    'name_provided', 'more_details', 'unclear'):
        needs_search = False

    # Skip search if we'd just probe for ambiguous trim
    if _is_ambiguous_trim_pivot(row, parsed, user_text):
        needs_search = False

    search_results = None
    available_models = None
    if needs_search:
        try:
            from sourcing_search import search as inv_search
            search_results = inv_search(row, limit=20)
        except Exception as e:
            print(f'[sourcing] search error id={request_id}: {e}', flush=True)
            search_results = []

        if not search_results and row.get('make'):
            try:
                from sourcing_search import suggest_models
                available_models = suggest_models(row['make'], model_hint=row.get('model'), limit=10)
            except Exception:
                available_models = None

    # 5. State machine picks the reply + next status
    reply, next_state, did_search = _decide(row, parsed, search_results, available_models, user_text)

    # 6. Append bot reply, persist
    row['conversation'] = _append_msg(row['conversation'], 'bot', reply,
                                       raw={'intent': intent,
                                            'changes': list(changes.keys()),
                                            'searched': did_search,
                                            'match_count': len(search_results) if search_results is not None else None})

    # Build the SQL UPDATE
    set_clauses, params = [], []
    for k, v in changes.items():
        set_clauses.append(f"{k} = %s")
        params.append(v)
    set_clauses += [
        "conversation = %s::jsonb",
        "status = %s",
        "last_msg_at = NOW()",
        "last_inbound_at = NOW()",
    ]
    params += [json.dumps(row['conversation']), next_state]

    # If transitioning to wishlist for the first time, set the 30d window.
    if next_state == 'wishlist':
        set_clauses.append("wishlist_until = COALESCE(wishlist_until, NOW() + INTERVAL '30 days')")

    if next_state == 'archived':
        set_clauses += ["archived_at = COALESCE(archived_at, NOW())",
                        "archive_reason = COALESCE(archive_reason, %s)"]
        params.append('user_intent_' + intent if intent in ('drop_it', 'stop') else 'user_intent_archived')

    sql = f"UPDATE sourcing_requests SET {', '.join(set_clauses)} WHERE id = %s"
    params.append(request_id)
    cur.execute(sql, params)
    db.commit()

    # 7. Send SMS (async)
    if send_sms and phone and reply:
        _send_sms_async(send_sms, phone, reply)

    print(f'[sourcing] turn id={request_id} intent={intent} '
          f'next={next_state} searched={did_search} '
          f'matches={len(search_results) if search_results is not None else "n/a"} '
          f'changes={list(changes.keys())}', flush=True)


# ── Main router ──────────────────────────────────────────────────────────
def try_handle_sourcing(from_phone, body, db, cur, intake_log_id=None,
                         num_media=0, send_sms=None):
    """Returns True if handled by sourcing flow; False to fall through to
    the existing bid-intake flow (Phase 1 / Phase 2). Bid-intake yield is
    UNCHANGED from prior versions — VIN/photo/non-gated phone always falls
    through with zero side effects."""
    if not _phone_allowed(from_phone):
        return False

    body_lc = (body or '').strip().lower()
    active = _find_active(cur, from_phone)

    # Stop / drop keyword fast-path
    if _handle_stop_or_drop(cur, from_phone, body_lc, active):
        db.commit()
        if send_sms and active:
            _send_sms_async(send_sms, from_phone, "ok, dropped. text us anytime.")
        print(f'[sourcing] {from_phone} dropped/stopped active={active["id"] if active else None}', flush=True)
        return True

    # Mid-conversation continuation — but yield to bid intake
    if active:
        if _looks_like_bid_intake(body, num_media):
            print(f'[sourcing] yielding to bid intake (VIN/photo) despite active sourcing id={active["id"]}', flush=True)
            return False

        # Matched threads → start a fresh row (carry name forward)
        if active['status'] == 'matched':
            print(f'[sourcing] active row id={active["id"]} is matched — archiving + fresh row', flush=True)
            cur.execute("UPDATE sourcing_requests SET status='archived', archived_at=NOW(), archive_reason='matched_completed' WHERE id=%s", (active['id'],))
            db.commit()
            cn = active.get('customer_name')
            cur.execute("INSERT INTO sourcing_requests (phone, status, conversation, last_msg_at, last_inbound_at, customer_name) VALUES (%s, 'gathering', '[]'::jsonb, NOW(), NOW(), %s) RETURNING id",
                        (from_phone, cn))
            new_id = cur.fetchone()['id']
            db.commit()
            row = {'id': new_id, 'phone': from_phone, 'status': 'gathering',
                   'conversation': [], 'customer_name': cn}
            _run_turn(db, cur, new_id, row, body or '', num_media=num_media,
                       send_sms=send_sms, phone=from_phone, fresh_row=True)
            return True

        row = dict(active)
        _run_turn(db, cur, active['id'], row, body or '',
                   num_media=num_media, send_sms=send_sms, phone=from_phone)
        return True

    # Cold inbound — yield to bid flow on VIN/photo
    if _looks_like_bid_intake(body, num_media):
        return False
    if not (body or '').strip():
        return False

    # Open a new sourcing request
    cur.execute("INSERT INTO sourcing_requests (phone, status, conversation, last_msg_at, last_inbound_at) VALUES (%s, 'gathering', '[]'::jsonb, NOW(), NOW()) RETURNING id",
                (from_phone,))
    new_id = cur.fetchone()['id']
    db.commit()
    row = {'id': new_id, 'phone': from_phone, 'status': 'gathering', 'conversation': []}
    _run_turn(db, cur, new_id, row, body or '', num_media=num_media,
               send_sms=send_sms, phone=from_phone, fresh_row=True)
    print(f'[sourcing] NEW id={new_id} phone={from_phone}', flush=True)
    return True
