-- 2026-05-19 — Dealer DB Graph System: Daily Newsletter
--
-- Long-form, narrative-style daily brief per dealer per day. Replaces
-- the dealer_intel_summary 3-card layout with a single article that
-- references yesterday's lot activity, this-week's price drops, peer
-- behaviour (anonymized — no dealer names), and acquisition memos.
--
-- Generated by dealer_intel_newsletter.py via Gemini Flash. The
-- structured sections live alongside the rendered article so the
-- portal can highlight specific sub-sections without re-prompting.

CREATE TABLE IF NOT EXISTS dealer_intel_newsletter (
    id              BIGSERIAL PRIMARY KEY,
    dealer_id       INTEGER     NOT NULL REFERENCES dealers(id) ON DELETE CASCADE,
    snapshot_date   DATE        NOT NULL,

    -- The newspaper-style article. Markdown OK, no inline HTML.
    headline        TEXT,
    lede            TEXT,              -- opening paragraph
    body_sections   JSONB NOT NULL DEFAULT '[]'::jsonb,
        -- [{title, body}, ...] — each section gets its own sub-header
        -- in the portal so the dealer can scan to "Price drops" or
        -- "What peers are doing"

    -- The raw inputs the model was fed (anonymized, peer names stripped)
    diff_snapshot   JSONB NOT NULL DEFAULT '{}'::jsonb,
    pattern_memory  JSONB NOT NULL DEFAULT '{}'::jsonb,
    peer_data       JSONB NOT NULL DEFAULT '{}'::jsonb,
    acquisition_data JSONB NOT NULL DEFAULT '{}'::jsonb,

    -- Same credibility footer info as before
    sample_sizes    JSONB       NOT NULL DEFAULT '{}'::jsonb,

    -- Audit / debugging
    model_name      TEXT,
    prompt_tokens   INTEGER,
    output_tokens   INTEGER,
    raw_response    JSONB,
    generation_ms   INTEGER,

    computed_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (dealer_id, snapshot_date)
);

CREATE INDEX IF NOT EXISTS idx_dealer_intel_newsletter_dealer_date
    ON dealer_intel_newsletter (dealer_id, snapshot_date DESC);
